package com.gymiq.enums;

public enum AuditAction {
    LOGIN,
    REGISTER,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_CHANGED,

    CREATE_USER,
    UPDATE_USER,
    DELETE_USER,

    CREATE_STUDENT,
    UPDATE_STUDENT,
    DEACTIVATE_STUDENT,
    ACTIVATE_STUDENT,
    ANONYMIZE_STUDENT,

    CREATE_INSTRUCTOR,
    UPDATE_INSTRUCTOR,
    DEACTIVATE_INSTRUCTOR,
    ACTIVATE_INSTRUCTOR,
    DELETE_INSTRUCTOR,

    CREATE_PLAN,
    UPDATE_PLAN,
    DEACTIVATE_PLAN,
    ACTIVATE_PLAN,
    DELETE_PLAN,

    CREATE_ENROLLMENT,
    UPDATE_ENROLLMENT_STATUS,
    RENEW_ENROLLMENT,

    PAY_PAYMENT,
    CHANGE_PAYMENT_STATUS,
    REFRESH_OVERDUE_PAYMENTS,
    GENERATE_MONTHLY_PAYMENTS,

    CHECK_IN,
    SELF_CHECK_IN,

    CREATE_EXERCISE,
    UPDATE_EXERCISE,
    DELETE_EXERCISE,

    CREATE_WORKOUT_SHEET,
    UPDATE_WORKOUT_SHEET,
    DEACTIVATE_WORKOUT_SHEET,

    ADD_WORKOUT_SHEET_EXERCISE,
    UPDATE_WORKOUT_SHEET_EXERCISE,
    DELETE_WORKOUT_SHEET_EXERCISE,

    GENERATE_RETENTION_ALERT,
    GENERATE_RETENTION_ALERTS,
    RESOLVE_RETENTION_ALERT
}
